# Generated by Django 2.0.5 on 2018-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcutid', models.IntegerField()),
                ('productname', models.CharField(max_length=30)),
                ('productcost', models.IntegerField()),
                ('productcolor', models.CharField(max_length=30)),
                ('productweight', models.IntegerField()),
            ],
        ),
    ]
