# Generated by Django 2.0.5 on 2018-10-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcutid',
            new_name='productid',
        ),
    ]
